maintainer       'Heavy Water Ops, Inc'
maintainer_email 'ops@hw-ops.com'
license          'Apache-2.0'
description      'Installs/Configures statsite'
name             'statsite'
version '0.0.3'

depends 'git'
depends 'python'
depends 'runit'
